# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
